version: "3.9"
services:
  builder:
    #image: maven:3.8.4-eclipse-temurin-17
    container_name: builderser
    volumes:
      - /home/revilo/Schreibtisch/Neuer Ordner (1)/test/:/app
      - /home/revilo/.m2/:/root/.m2/
      - /var/run/docker.sock:/var/run/docker.sock
    build: ./builder/
    command: bash -c "
        ls /bin;
        docker --version;
        docker images;
        cd /app ;
        ls -lisa;
        mvn clean compile jib:dockerBuild;
      "